apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJibTkwYUdWeWJHRnVaRHBuYUhCZlJXVnRjWGxaVEZSVVptUlFaMWwzV0V4c2QwUm5hRlZFVkhJeFJXcHNNRFZPVEVGWCIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==
type: kubernetes.io/dockerconfigjson
