apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJibTkwYUdWeWJHRnVaRHBuYUhCZlJXVnRjWGxaVEZSVVptUlFaMWwzV0V4c2QwUm5hRlZFVkhJeFJXcHNNRFZPVEVGWCJ9fX0=
type: kubernetes.io/dockerconfigjson
